// Generated stub copied from project root `uniwind.d.ts` to satisfy Metro/Tailwind tooling
// If you're running into missing types during build, regenerate using Uniwind tools.

// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'lavender-light', 'lavender-dark', 'mint-light', 'mint-dark', 'sky-light', 'sky-dark']
    }
}

export { }

